### ISSUE TITLE
great use of inheritance

### ISSUE THREAD

**Issue by rimmesbe** [mode-js/prj-rev-bwfs-dasmoto#3]
This is a great way to set the pages default font. You should be able to remove the font-family style from #price now.

https://github.com/mode-js/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/index.css#L2-L4

**Comment by mode-js** [comment]
This has been fixed now.  I played around with changing the font for the price to Lato or Roboto (google fonts) for the price sections but then switched it back.  I like how the inspector crosses out certain styles and tells me what items have been overrulled by other items.
